# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee80c8d8d68fec8a8430c6e1b33e5a7b650663f4a7b7107053a0f714516dfc99872d0a9b384681421e932143801b2270bcf18f6778ad0d827321b39d2bc8a3e8

test:
  secret_key_base: d0a1f74458f711b69c41b5db7479e8a912424ca2d12e88529c4b0316116eeb30455389b025c5d1c3d6a0009827d0e92898a41aa6036b697e3ee1c378f7747ec5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
